# Site settings
title: でんきうお水族館
description: 電気魚のWebサイト
twitter_username: denkiuo604
github_username:  denkiuo604
locale: ja_JP
lang: ja

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-target-blank